version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/db
    environment:
      - DEBUG=0
    command: sh -c "python manage.py collectstatic --noinput && gunicorn menu_prj.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  sqlite_data: